In [ ]:
d_model = 3  # Size of the embeddings (features)
nhead = 1  # Number of attention heads
num_encoder_layers = 1  # Number of encoder layers

# Define Transformer Encoder Layer
encoder_layer = nn.TransformerEncoderLayer(d_model=d_model, nhead=nhead, dropout=0, batch_first=True)
transformer_encoder = nn.TransformerEncoder(encoder_layer, num_layers=num_encoder_layers)

transformer_encoder.eval()


# Test with different seq_len and batch_size
# input_tensor1 = torch.Tensor([[[7],
#                                [5]],
                                    
#                                     [[9],
#                                      [11]]])

# input_tensor2 = torch.Tensor([[[7],
#                                [5]]])

input_tensor1 = torch.Tensor([[[1, 2, 7],
                                     [11, 5, 6]],
                                    
                                    [[7, 8, 9],
                                     [10, 11, 12]]])

input_tensor2 = torch.Tensor([[[1, 2, 7],
                                 [11, 5, 6]]])

# input_tensor1 = torch.Tensor([[[0.123]],
                                
#                               [[0.087]]])

# input_tensor2 = torch.Tensor([[[0.123],
#                                [0.9]],
                              
#                               [[0.087],
#                                [0.11]]])

print(input_tensor1.equal(input_tensor2))

output1 = encoder_layer(input_tensor1)
output2 = encoder_layer(input_tensor2)

print(input_tensor1.shape)
print(input_tensor2.shape)
print()

print(output1)
print()
print(output2)
print()

print(output1.shape)
print(output2.shape)
print(output1.equal(output2))

In [3]:
import torch
import numpy as np
x = torch.Tensor([[1,2,3],[4,5,6]])
print(x)
print(x.shape)

x = x.unsqueeze(0)
print(x)
print(x.shape)

x = x.squeeze(0)
print(x)
print(x.shape)

tensor([[1., 2., 3.],
        [4., 5., 6.]])
torch.Size([2, 3])
tensor([[[1., 2., 3.],
         [4., 5., 6.]]])
torch.Size([1, 2, 3])
tensor([[1., 2., 3.],
        [4., 5., 6.]])
torch.Size([2, 3])
